"""add missing indexes (users.id, shopping_list_recipes composite)

Revision ID: a36c149a93d4
Revises: 20260603_0012
Create Date: 2026-06-13 03:50:16.413237

Intended diff vs the schema produced by migration 20260603_0012:
  - the composite index on shopping_list_recipes(shopping_list_id, recipe_id)
    that is declared in ShoppingListRecipe.__table_args__ but never created.
  - the index on users.id that is declared in User.id (index=True) but never
    created (SQLite PK is auto-indexed, but the model explicitly asks for it).

The autogenerated version of this migration also tried to drop+recreate the
user_favorites foreign keys with ON DELETE CASCADE — but those FKs were
already CASCADE at revision 20260603_0012, so those ops were no-ops that
additionally crashed SQLite (op.drop_constraint is unsupported without
batch_alter_table). Dropped them. Same for op.alter_column on users.id
(already NOT NULL).

SQLite-proof: only CREATE INDEX / DROP INDEX, both first-class SQLite ops,
no batch_alter_table needed.
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a36c149a93d4'
down_revision: Union[str, Sequence[str], None] = '20260603_0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index(
        'ix_shopping_list_recipes_list_recipe',
        'shopping_list_recipes',
        ['shopping_list_id', 'recipe_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_users_id'),
        'users',
        ['id'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_shopping_list_recipes_list_recipe', table_name='shopping_list_recipes')