"""empty message

Revision ID: a36c149a93d4
Revises: 20260603_0012
Create Date: 2026-06-13 03:50:16.413237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36c149a93d4'
down_revision: Union[str, Sequence[str], None] = '20260603_0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shopping_list_recipes_list_recipe', 'shopping_list_recipes', ['shopping_list_id', 'recipe_id'], unique=False)
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorites', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_favorites', 'recipes', ['recipe_id'], ['id'])
    op.drop_index('ix_shopping_list_recipes_list_recipe', table_name='shopping_list_recipes')
    # ### end Alembic commands ###
